
name: "lixianla签到"

on:
  workflow_dispatch:
  schedule:
    # 每天国际时间 16:00 运行一次, 中国时间 00:00
    - cron: '00 16 * * *'
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: '代码检查'
        uses: actions/checkout@v2
      - name: '初始化Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: '安装依赖包'
        run: |
          pip install --upgrade pip
          python -m pip install --upgrade requests
          pip install beautifulsoup4
          pip install urllib.parse
         
      - name: '开始签到'
        env:
          requestUrl: ${{ secrets.requestUrl }}
          Cookie: ${{ secrets.Cookie }}
          PushToken: ${{ secrets.PushToken }}
          
        run: python main.py
